ALTER TABLE scores
ADD COLUMN weighted_points INTEGER NOT NULL DEFAULT 0,
ADD COLUMN played_on       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN duration        BIGINT NOT NULL DEFAULT 0,
ADD COLUMN categories      INTEGER[] NOT NULL DEFAULT '{}';